import type { ImageSourcePropType } from "react-native";

export type PhoneCountry = {
  name: string;
  callingCode: string;
  flag: ImageSourcePropType;
};

export function parseCallingCodes(callingCode: string): string[] {
  return callingCode
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

export function primaryCallingCode(callingCode: string): string {
  return parseCallingCodes(callingCode)[0] ?? callingCode.trim();
}

export const FLAG: Record<string, ImageSourcePropType> = {
  Afghanistan: require("../../assets/icons/flag/Afghanistan.jpg"),
  Albania: require("../../assets/icons/flag/Albania.jpg"),
  Algeria: require("../../assets/icons/flag/Algeria.png"),
  AmericanSamoa: require("../../assets/icons/flag/American_Samoa.jpg"),
  Andorra: require("../../assets/icons/flag/Andorra.jpg"),
  Angola: require("../../assets/icons/flag/Angola.jpg"),
  Antiguaandbarbuda: require("../../assets/icons/flag/Antiguaandbarbuda.jpg"),
  Argentina: require("../../assets/icons/flag/Argentina.jpg"),
  Armenia: require("../../assets/icons/flag/Armenia.jpg"),
  Australia: require("../../assets/icons/flag/Australia.jpg"),
  Austria: require("../../assets/icons/flag/Austria.jpg"),
  Bahamas: require("../../assets/icons/flag/Bahamas.jpg"),
  Bangladesh: require("../../assets/icons/flag/Bangladesh.jpg"),
  Barbados: require("../../assets/icons/flag/Barbados.jpg"),
  Belarus: require("../../assets/icons/flag/Belarus.jpg"),
  Belgium: require("../../assets/icons/flag/Belgium.jpg"),
  Belize: require("../../assets/icons/flag/Belize.jpg"),
  Benin: require("../../assets/icons/flag/Benin.jpg"),
  Bhutan: require("../../assets/icons/flag/Bhutan.jpg"),
  Bolivia: require("../../assets/icons/flag/Bolivia.jpg"),
  Bosniaandherzegovina: require("../../assets/icons/flag/Bosniaandherzegovina.jpg"),
  Botswana: require("../../assets/icons/flag/Botswana.jpg"),
  Brazil: require("../../assets/icons/flag/Brazil.jpg"),
  Britain: require("../../assets/icons/flag/Britain.jpg"),
  Brunei: require("../../assets/icons/flag/Brunei.jpg"),
  Bulgaria: require("../../assets/icons/flag/Bulgaria.jpg"),
  Burkinafaso: require("../../assets/icons/flag/Burkinafaso.jpg"),
  Burundi: require("../../assets/icons/flag/Burundi.jpg"),
  Cambodia: require("../../assets/icons/flag/Cambodia.jpg"),
  Cameroon: require("../../assets/icons/flag/Cameroon.jpg"),
  Canada: require("../../assets/icons/flag/Canada.jpg"),
  Capeverde: require("../../assets/icons/flag/Capeverde.jpg"),
  Centralafricanrepublic: require("../../assets/icons/flag/Centralafricanrepublic.jpg"),
  Chad: require("../../assets/icons/flag/Chad.jpg"),
  Chile: require("../../assets/icons/flag/Chile.jpg"),
  China: require("../../assets/icons/flag/China.jpg"),
  Colombia: require("../../assets/icons/flag/Colombia.jpg"),
  Comoros: require("../../assets/icons/flag/Comoros.jpg"),
  Congo: require("../../assets/icons/flag/Congo.jpg"),
  Costarica: require("../../assets/icons/flag/Costarica.jpg"),
  Croatia: require("../../assets/icons/flag/Croatia.jpg"),
  Cuba: require("../../assets/icons/flag/Cuba.jpg"),
  Cyprus: require("../../assets/icons/flag/Cyprus.jpg"),
  Czechrepublic: require("../../assets/icons/flag/Czechrepublic.jpg"),
  CoteDIvoire: require("../../assets/icons/flag/Côted’Ivoire.jpg"),
  Democraticrepublicofthecongo: require("../../assets/icons/flag/Democraticrepublicofthecongo.jpg"),
  Denmark: require("../../assets/icons/flag/Denmark.jpg"),
  Djibouti: require("../../assets/icons/flag/Djibouti.jpg"),
  Dominicanrepublic: require("../../assets/icons/flag/Dominicanrepublic.jpg"),
  Ecuador: require("../../assets/icons/flag/Ecuador.jpg"),
  Egypt: require("../../assets/icons/flag/Egypt.jpg"),
  Elsalvador: require("../../assets/icons/flag/Elsalvador.jpg"),
  Equatorialguinea: require("../../assets/icons/flag/Equatorialguinea.jpg"),
  Estonia: require("../../assets/icons/flag/Estonia.jpg"),
  Ethiopia: require("../../assets/icons/flag/Ethiopia.jpg"),
  Falkland: require("../../assets/icons/flag/Falkland.jpg"),
  Fiji: require("../../assets/icons/flag/Fiji.jpg"),
  Finland: require("../../assets/icons/flag/Finland.jpg"),
  France: require("../../assets/icons/flag/France.jpg"),
  Gabon: require("../../assets/icons/flag/Gabon.jpg"),
  Gambia: require("../../assets/icons/flag/Gambia.jpg"),
  Germany: require("../../assets/icons/flag/Germany.jpg"),
  Ghana: require("../../assets/icons/flag/Ghana.jpg"),
  Gibraltar: require("../../assets/icons/flag/Gibraltar.jpg"),
  Greece: require("../../assets/icons/flag/Greece.jpg"),
  Grenada: require("../../assets/icons/flag/Grenada.jpg"),
  Guadeloupe: require("../../assets/icons/flag/Guadeloupe.jpg"),
  Guatemala: require("../../assets/icons/flag/Guatemala.jpg"),
  Guinea: require("../../assets/icons/flag/Guinea.jpg"),
  Guineabissau: require("../../assets/icons/flag/Guineabissau.jpg"),
  Guyana: require("../../assets/icons/flag/Guyana.jpg"),
  Haiti: require("../../assets/icons/flag/Haiti.jpg"),
  Honduras: require("../../assets/icons/flag/Honduras.jpg"),
  Hungary: require("../../assets/icons/flag/Hungary.jpg"),
  Iceland: require("../../assets/icons/flag/Iceland.jpg"),
  India: require("../../assets/icons/flag/India.jpg"),
  Indonesia: require("../../assets/icons/flag/Indonesia.jpg"),
  Iran: require("../../assets/icons/flag/Iran.jpg"),
  Ireland: require("../../assets/icons/flag/Ireland.jpg"),
  Israel: require("../../assets/icons/flag/Israel.jpg"),
  Italy: require("../../assets/icons/flag/Italy.jpg"),
  Jamaica: require("../../assets/icons/flag/Jamaica.jpg"),
  Japan: require("../../assets/icons/flag/Japan.jpg"),
  Jordan: require("../../assets/icons/flag/Jordan.jpg"),
  Kazakhstan: require("../../assets/icons/flag/Kazakhstan.jpg"),
  Kenya: require("../../assets/icons/flag/Kenya.jpg"),
  Kuwait: require("../../assets/icons/flag/Kuwait.jpg"),
  Kyrgyzstan: require("../../assets/icons/flag/Kyrgyzstan.jpg"),
  Laos: require("../../assets/icons/flag/Laos.jpg"),
  Latvia: require("../../assets/icons/flag/Latvia.jpg"),
  Lebanon: require("../../assets/icons/flag/Lebanon.jpg"),
  Lesotho: require("../../assets/icons/flag/Lesotho.jpg"),
  Liberia: require("../../assets/icons/flag/Liberia.jpg"),
  Libya: require("../../assets/icons/flag/Libya.jpg"),
  Liechtenstein: require("../../assets/icons/flag/Liechtenstein.jpg"),
  Lithuania: require("../../assets/icons/flag/Lithuania.jpg"),
  Luxembourg: require("../../assets/icons/flag/Luxembourg.jpg"),
  Macedonia: require("../../assets/icons/flag/Macedonia.jpg"),
  Madagascar: require("../../assets/icons/flag/Madagascar.jpg"),
  Malawi: require("../../assets/icons/flag/Malawi.jpg"),
  Malaysia: require("../../assets/icons/flag/Malaysia.jpg"),
  Maldives: require("../../assets/icons/flag/Maldives.jpg"),
  Mali: require("../../assets/icons/flag/Mali.jpg"),
  Malta: require("../../assets/icons/flag/Malta.jpg"),
  Martinique: require("../../assets/icons/flag/Martinique.jpg"),
  Mauritania: require("../../assets/icons/flag/Mauritania.jpg"),
  Mauritius: require("../../assets/icons/flag/Mauritius.jpg"),
  Mexico: require("../../assets/icons/flag/Mexico.jpg"),
  Moldova: require("../../assets/icons/flag/Moldova.jpg"),
  Monaco: require("../../assets/icons/flag/Monaco.jpg"),
  Mongolia: require("../../assets/icons/flag/Mongolia.jpg"),
  Montenegro: require("../../assets/icons/flag/Montenegro.jpg"),
  Morocco: require("../../assets/icons/flag/Morocco.jpg"),
  Mozambique: require("../../assets/icons/flag/Mozambique.jpg"),
  Myanmar: require("../../assets/icons/flag/Myanmar.jpg"),
  Namibia: require("../../assets/icons/flag/Namibia.jpg"),
  Nepal: require("../../assets/icons/flag/Nepal.jpg"),
  Netherlands: require("../../assets/icons/flag/Netherlands.jpg"),
  Newzealand: require("../../assets/icons/flag/Newzealand.jpg"),
  Nicaragua: require("../../assets/icons/flag/Nicaragua.jpg"),
  Niger: require("../../assets/icons/flag/Niger.jpg"),
  Nigeria: require("../../assets/icons/flag/Nigeria.jpg"),
  Norway: require("../../assets/icons/flag/Norway.jpg"),
  Oman: require("../../assets/icons/flag/Oman.jpg"),
  Pakistan: require("../../assets/icons/flag/Pakistan.jpg"),
  Panama: require("../../assets/icons/flag/Panama.jpg"),
  Papuanewguinea: require("../../assets/icons/flag/Papuanewguinea.jpg"),
  Paraguay: require("../../assets/icons/flag/Paraguay.jpg"),
  Peru: require("../../assets/icons/flag/Peru.jpg"),
  Philippines: require("../../assets/icons/flag/Philippines.jpg"),
  Poland: require("../../assets/icons/flag/Poland.jpg"),
  Portugal: require("../../assets/icons/flag/Portugal.jpg"),
  Qatar: require("../../assets/icons/flag/Qatar.jpg"),
  Romania: require("../../assets/icons/flag/Romania.jpg"),
  Russia: require("../../assets/icons/flag/Russia.jpg"),
  Rwanda: require("../../assets/icons/flag/Rwanda.jpg"),
  Samoa: require("../../assets/icons/flag/Samoa.jpg"),
  Sanmarino: require("../../assets/icons/flag/Sanmarino.jpg"),
  Saudiarabia: require("../../assets/icons/flag/Saudiarabia.jpg"),
  Senegal: require("../../assets/icons/flag/Senegal.jpg"),
  Serbia: require("../../assets/icons/flag/Serbia.jpg"),
  Seychelles: require("../../assets/icons/flag/Seychelles.jpg"),
  SierraLeone: require("../../assets/icons/flag/SierraLeone.jpg"),
  Singapore: require("../../assets/icons/flag/Singapore.jpg"),
  Slovakia: require("../../assets/icons/flag/Slovakia.jpg"),
  Slovenia: require("../../assets/icons/flag/Slovenia.jpg"),
  Solomonislands: require("../../assets/icons/flag/Solomonislands.jpg"),
  Somalia: require("../../assets/icons/flag/Somalia.jpg"),
  Southafrica: require("../../assets/icons/flag/Southafrica.jpg"),
  Southkorea: require("../../assets/icons/flag/Southkorea.jpg"),
  Spain: require("../../assets/icons/flag/Spain.jpg"),
  Srilanka: require("../../assets/icons/flag/Srilanka.jpg"),
  Sudan: require("../../assets/icons/flag/Sudan.jpg"),
  Suriname: require("../../assets/icons/flag/Suriname.jpg"),
  Swaziland: require("../../assets/icons/flag/Swaziland.jpg"),
  Sweden: require("../../assets/icons/flag/Sweden.jpg"),
  Switzerland: require("../../assets/icons/flag/Switzerland.jpg"),
  Syria: require("../../assets/icons/flag/Syria.jpg"),
  SaoTomeandPrincipe: require("../../assets/icons/flag/SãoToméandPríncipe.jpg"),
  Taiwan: require("../../assets/icons/flag/Taiwan.jpg"),
  Tajikistan: require("../../assets/icons/flag/Tajikistan.jpg"),
  Tanzania: require("../../assets/icons/flag/Tanzania.jpg"),
  Thailand: require("../../assets/icons/flag/Thailand.jpg"),
  Togo: require("../../assets/icons/flag/Togo.jpg"),
  Tonga: require("../../assets/icons/flag/Tonga.jpg"),
  Tunisia: require("../../assets/icons/flag/Tunisia.jpg"),
  Turkey: require("../../assets/icons/flag/Turkey.jpg"),
  Turkmenistan: require("../../assets/icons/flag/Turkmenistan.jpg"),
  Tuvalu: require("../../assets/icons/flag/Tuvalu.jpg"),
  UAE: require("../../assets/icons/flag/UAE.jpg"),
  USA: require("../../assets/icons/flag/USA.jpg"),
  Uganda: require("../../assets/icons/flag/Uganda.jpg"),
  Ukraine: require("../../assets/icons/flag/Ukraine.jpg"),
  Uruguay: require("../../assets/icons/flag/Uruguay.jpg"),
  Uzbekistan: require("../../assets/icons/flag/Uzbekistan.jpg"),
  Vanuatu: require("../../assets/icons/flag/Vanuatu.jpg"),
  Venezuela: require("../../assets/icons/flag/Venezuela.jpg"),
  Vietnam: require("../../assets/icons/flag/Vietnam.jpg"),
  Yemen: require("../../assets/icons/flag/Yemen.jpg"),
  Zambia: require("../../assets/icons/flag/Zambia.jpg"),
  Zimbabwe: require("../../assets/icons/flag/Zimbabwe.jpg"),

  ChagosArchipelago: require("../../assets/icons/flag/Chagos_Archipelago.png"),
  ReunionIsland: require("../../assets/icons/flag/Reunion_Island.png"),
  Aruba: require("../../assets/icons/flag/Aruba.png"),
  FaeroeIslands: require("../../assets/icons/flag/Faeroe_Islands.png"),
  Greenland: require("../../assets/icons/flag/Greenland.png"),
  Bermuda: require("../../assets/icons/flag/Bermuda.png"),
  FrenchGuiana: require("../../assets/icons/flag/French_Guiana.png"),
  NewCaledonia: require("../../assets/icons/flag/New_Caledonia.png"),
  FrenchPolynesia: require("../../assets/icons/flag/French_Polynesia.png"),
  MidwayIslands: require("../../assets/icons/flag/Midway_Islands.png"),
  HongKong: require("../../assets/icons/flag/Hong_Kong.png"),
  Macau: require("../../assets/icons/flag/Macau.png"),
  Iraq: require("../../assets/icons/flag/Iraq.png"),
  Bahrain: require("../../assets/icons/flag/Bahrain.png"),
  Azerbaijan: require("../../assets/icons/flag/Azerbaijan.png"),
  Georgia: require("../../assets/icons/flag/Georgia.png"),
  Anguilla: require("../../assets/icons/flag/Anguilla.png"),
  BritishVirginIslands: require("../../assets/icons/flag/British_Virgin_Islands.png"),
  USVirginIslands: require("../../assets/icons/flag/US_Virgin_Islands.png"),
  CaymanIslands: require("../../assets/icons/flag/Cayman_Islands.png"),
  TurksAndCaicosIslands: require("../../assets/icons/flag/Turks_and_Caicos_Islands.png"),
  Montserrat: require("../../assets/icons/flag/Montserrat.png"),
  NorthernMarianaIslands: require("../../assets/icons/flag/Northern_Mariana_Islands.png"),
  Guam: require("../../assets/icons/flag/Guam.png"),
  SaintLucia: require("../../assets/icons/flag/Saint_Lucia.png"),
  Dominica: require("../../assets/icons/flag/Dominica.png"),
  SaintVincentAndTheGrenadines: require("../../assets/icons/flag/Saint_Vincent_and_the_Grenadines.png"),
  PuertoRico: require("../../assets/icons/flag/Puerto_Rico.png"),
  TrinidadAndTobago: require("../../assets/icons/flag/Trinidad_and_Tobago.png"),
  SaintKittsAndNevis: require("../../assets/icons/flag/Saint_Kitts_and_Nevis.png"),
};

export const PHONE_COUNTRIES: PhoneCountry[] = [
  { name: "Canada", callingCode: "1", flag: FLAG.Canada },
  { name: "United States", callingCode: "1", flag: FLAG.USA },
  { name: "Russia", callingCode: "7", flag: FLAG.Russia },

  { name: "Kazakhstan", callingCode: "7", flag: FLAG.Kazakhstan },

  { name: "Egypt", callingCode: "20", flag: FLAG.Egypt },
  { name: "South Africa", callingCode: "27", flag: FLAG.Southafrica },
  { name: "Greece", callingCode: "30", flag: FLAG.Greece },
  { name: "Netherlands", callingCode: "31", flag: FLAG.Netherlands },
  { name: "Belgium", callingCode: "32", flag: FLAG.Belgium },
  { name: "France", callingCode: "33", flag: FLAG.France },
  { name: "Spain", callingCode: "34", flag: FLAG.Spain },
  { name: "Hungary", callingCode: "36", flag: FLAG.Hungary },
  { name: "Italy", callingCode: "39", flag: FLAG.Italy },
  { name: "Romania", callingCode: "40", flag: FLAG.Romania },
  { name: "Switzerland", callingCode: "41", flag: FLAG.Switzerland },
  { name: "Austria", callingCode: "43", flag: FLAG.Austria },
  { name: "United Kingdom", callingCode: "44", flag: FLAG.Britain },
  { name: "Denmark", callingCode: "45", flag: FLAG.Denmark },
  { name: "Sweden", callingCode: "46", flag: FLAG.Sweden },
  { name: "Norway", callingCode: "47", flag: FLAG.Norway },
  { name: "Poland", callingCode: "48", flag: FLAG.Poland },
  { name: "Germany", callingCode: "49", flag: FLAG.Germany },
  { name: "Peru", callingCode: "51", flag: FLAG.Peru },
  { name: "Mexico", callingCode: "52", flag: FLAG.Mexico },
  { name: "Cuba", callingCode: "53", flag: FLAG.Cuba },
  { name: "Argentina", callingCode: "54", flag: FLAG.Argentina },
  { name: "Brazil", callingCode: "55", flag: FLAG.Brazil },
  { name: "Chile", callingCode: "56", flag: FLAG.Chile },
  { name: "Colombia", callingCode: "57", flag: FLAG.Colombia },
  { name: "Venezuela", callingCode: "58", flag: FLAG.Venezuela },
  { name: "Malaysia", callingCode: "60", flag: FLAG.Malaysia },
  { name: "Australia", callingCode: "61", flag: FLAG.Australia },
  { name: "Indonesia", callingCode: "62", flag: FLAG.Indonesia },
  { name: "Philippines", callingCode: "63", flag: FLAG.Philippines },
  { name: "New Zealand", callingCode: "64", flag: FLAG.Newzealand },
  { name: "Singapore", callingCode: "65", flag: FLAG.Singapore },
  { name: "Thailand", callingCode: "66", flag: FLAG.Thailand },
  { name: "Japan", callingCode: "81", flag: FLAG.Japan },
  { name: "South Korea", callingCode: "82", flag: FLAG.Southkorea },
  { name: "Vietnam", callingCode: "84", flag: FLAG.Vietnam },
  { name: "China", callingCode: "86", flag: FLAG.China },
  { name: "Turkey", callingCode: "90", flag: FLAG.Turkey },
  { name: "India", callingCode: "91", flag: FLAG.India },
  { name: "Pakistan", callingCode: "92", flag: FLAG.Pakistan },
  { name: "Afghanistan", callingCode: "93", flag: FLAG.Afghanistan },
  { name: "Sri Lanka", callingCode: "94", flag: FLAG.Srilanka },
  { name: "Myanmar (Burma)", callingCode: "95", flag: FLAG.Myanmar },
  { name: "Iran", callingCode: "98", flag: FLAG.Iran },

  { name: "Morocco", callingCode: "212", flag: FLAG.Morocco },
  { name: "Algeria", callingCode: "213", flag: FLAG.Algeria },
  { name: "Tunisia", callingCode: "216", flag: FLAG.Tunisia },
  { name: "Libya", callingCode: "218", flag: FLAG.Libya },
  { name: "Gambia", callingCode: "220", flag: FLAG.Gambia },
  { name: "Senegal", callingCode: "221", flag: FLAG.Senegal },
  { name: "Mauritania", callingCode: "222", flag: FLAG.Mauritania },
  { name: "Mali", callingCode: "223", flag: FLAG.Mali },
  { name: "Guinea", callingCode: "224", flag: FLAG.Guinea },
  { name: "Côte d’Ivoire", callingCode: "225", flag: FLAG.CoteDIvoire },
  { name: "Ivory Coast", callingCode: "225", flag: FLAG.CoteDIvoire },
  { name: "Burkina Faso", callingCode: "226", flag: FLAG.Burkinafaso },
  { name: "Niger Republic", callingCode: "227", flag: FLAG.Niger },
  { name: "Togo", callingCode: "228", flag: FLAG.Togo },
  { name: "Benin", callingCode: "229", flag: FLAG.Benin },
  { name: "Mauritius", callingCode: "230", flag: FLAG.Mauritius },
  { name: "Liberia", callingCode: "231", flag: FLAG.Liberia },
  { name: "Sierra Leone", callingCode: "232", flag: FLAG.SierraLeone },
  { name: "Ghana", callingCode: "233", flag: FLAG.Ghana },
  { name: "Nigeria", callingCode: "234", flag: FLAG.Nigeria },
  { name: "Chad", callingCode: "235", flag: FLAG.Chad },
  {
    name: "Central African Republic",
    callingCode: "236",
    flag: FLAG.Centralafricanrepublic,
  },
  { name: "Cameroon", callingCode: "237", flag: FLAG.Cameroon },
  { name: "Cape Verde", callingCode: "238", flag: FLAG.Capeverde },
  {
    name: "São Tomé and Príncipe",
    callingCode: "239",
    flag: FLAG.SaoTomeandPrincipe,
  },
  {
    name: "Equatorial Guinea",
    callingCode: "240",
    flag: FLAG.Guinea,
  },
  { name: "Gabon", callingCode: "241", flag: FLAG.Gabon },
  { name: "Congo", callingCode: "242", flag: FLAG.Congo },
  {
    name: "Congo, Dem. Rep. of",
    callingCode: "243",
    flag: FLAG.Democraticrepublicofthecongo,
  },

  { name: "Bahamas", callingCode: "1242", flag: FLAG.Bahamas },
  {
    name: "Zaire",
    callingCode: "243",
    flag: FLAG.Democraticrepublicofthecongo,
  },

  { name: "Angola", callingCode: "244", flag: FLAG.Angola },
  { name: "Guinea-Bissau", callingCode: "245", flag: FLAG.Guineabissau },

  {
    name: "Chagos Archipelago",
    callingCode: "246",
    flag: FLAG.ChagosArchipelago,
  },

  { name: "Barbados", callingCode: "1246", flag: FLAG.Barbados },

  { name: "Seychelles", callingCode: "248", flag: FLAG.Seychelles },
  { name: "Sudan", callingCode: "249", flag: FLAG.Sudan },
  { name: "Rwanda", callingCode: "250", flag: FLAG.Rwanda },
  { name: "Ethiopia", callingCode: "251", flag: FLAG.Ethiopia },
  { name: "Somalia", callingCode: "252", flag: FLAG.Somalia },
  { name: "Djibouti", callingCode: "253", flag: FLAG.Djibouti },
  { name: "Kenya", callingCode: "254", flag: FLAG.Kenya },
  { name: "Tanzania", callingCode: "255", flag: FLAG.Tanzania },
  { name: "Uganda", callingCode: "256", flag: FLAG.Uganda },
  { name: "Burundi", callingCode: "257", flag: FLAG.Burundi },
  { name: "Mozambique", callingCode: "258", flag: FLAG.Mozambique },
  { name: "Zambia", callingCode: "260", flag: FLAG.Zambia },
  { name: "Madagascar", callingCode: "261", flag: FLAG.Madagascar },
  { name: "Reunion Island", callingCode: "262", flag: FLAG.ReunionIsland },
  { name: "Zimbabwe", callingCode: "263", flag: FLAG.Zimbabwe },
  { name: "Namibia", callingCode: "264", flag: FLAG.Namibia },
  { name: "Malawi", callingCode: "265", flag: FLAG.Malawi },
  { name: "Lesotho", callingCode: "266", flag: FLAG.Lesotho },
  { name: "Botswana", callingCode: "267", flag: FLAG.Botswana },
  { name: "Swaziland", callingCode: "268", flag: FLAG.Swaziland },
  { name: "Comoros", callingCode: "269", flag: FLAG.Comoros },

  { name: "Aruba", callingCode: "297", flag: FLAG.Aruba },
  { name: "Faeroe Islands", callingCode: "298", flag: FLAG.FaeroeIslands },
  { name: "Greenland", callingCode: "299", flag: FLAG.Greenland },

  { name: "Gibraltar", callingCode: "350", flag: FLAG.Gibraltar },
  { name: "Portugal", callingCode: "351", flag: FLAG.Portugal },
  { name: "Luxembourg", callingCode: "352", flag: FLAG.Luxembourg },
  { name: "Ireland", callingCode: "353", flag: FLAG.Ireland },
  { name: "Iceland", callingCode: "354", flag: FLAG.Iceland },
  { name: "Albania", callingCode: "355", flag: FLAG.Albania },
  { name: "Malta", callingCode: "356", flag: FLAG.Malta },
  { name: "Cyprus", callingCode: "357", flag: FLAG.Cyprus },
  { name: "Finland", callingCode: "358", flag: FLAG.Finland },
  { name: "Bulgaria", callingCode: "359", flag: FLAG.Bulgaria },
  { name: "Lithuania", callingCode: "370", flag: FLAG.Lithuania },
  { name: "Latvia", callingCode: "371", flag: FLAG.Latvia },
  { name: "Estonia", callingCode: "372", flag: FLAG.Estonia },
  { name: "Moldova", callingCode: "373", flag: FLAG.Moldova },
  { name: "Armenia", callingCode: "374", flag: FLAG.Armenia },
  { name: "Belarus", callingCode: "375", flag: FLAG.Belarus },
  { name: "Andorra", callingCode: "376", flag: FLAG.Andorra },
  { name: "Monaco", callingCode: "377", flag: FLAG.Monaco },
  { name: "San Marino", callingCode: "378", flag: FLAG.Sanmarino },
  { name: "Ukraine", callingCode: "380", flag: FLAG.Ukraine },

  { name: "Montenegro", callingCode: "382", flag: FLAG.Montenegro },

  { name: "Serbia", callingCode: "381", flag: FLAG.Serbia },

  { name: "Croatia", callingCode: "385", flag: FLAG.Croatia },
  { name: "Slovenia", callingCode: "386", flag: FLAG.Slovenia },
  {
    name: "Bosnia & Herzegovina",
    callingCode: "387",
    flag: FLAG.Bosniaandherzegovina,
  },
  { name: "Macedonia", callingCode: "389", flag: FLAG.Macedonia },

  { name: "Czech Republic", callingCode: "420", flag: FLAG.Czechrepublic },
  { name: "Slovak Republic", callingCode: "421", flag: FLAG.Slovakia },
  { name: "Liechtenstein", callingCode: "423", flag: FLAG.Liechtenstein },

  { name: "Bermuda", callingCode: "1441", flag: FLAG.Bermuda },

  { name: "Falkland Islands", callingCode: "500", flag: FLAG.Falkland },
  { name: "Belize", callingCode: "501", flag: FLAG.Belize },
  { name: "Guatemala", callingCode: "502", flag: FLAG.Guatemala },
  { name: "El Salvador", callingCode: "503", flag: FLAG.Elsalvador },
  { name: "Honduras", callingCode: "504", flag: FLAG.Honduras },
  { name: "Nicaragua", callingCode: "505", flag: FLAG.Nicaragua },
  { name: "Costa Rica", callingCode: "506", flag: FLAG.Costarica },
  { name: "Panama", callingCode: "507", flag: FLAG.Panama },
  { name: "Haiti", callingCode: "509", flag: FLAG.Haiti },

  { name: "Guadeloupe", callingCode: "590", flag: FLAG.Guadeloupe },
  { name: "Bolivia", callingCode: "591", flag: FLAG.Bolivia },
  { name: "Guyana", callingCode: "592", flag: FLAG.Guyana },
  { name: "Ecuador", callingCode: "593", flag: FLAG.Ecuador },
  { name: "French Guiana", callingCode: "594", flag: FLAG.FrenchGuiana },
  { name: "Paraguay", callingCode: "595", flag: FLAG.Paraguay },
  {
    name: "French Antilles",
    callingCode: "596",
    flag: require("../../assets/icons/flag/Antilles.jpg"),
  },
  { name: "Martinique", callingCode: "596", flag: FLAG.Martinique },
  { name: "Suriname", callingCode: "597", flag: FLAG.Suriname },
  { name: "Uruguay", callingCode: "598", flag: FLAG.Uruguay },
  {
    name: "Netherlands Antilles",
    callingCode: "599",
    flag: require("../../assets/icons/flag/Antilles.jpg"),
  },

  { name: "Brunei Darussalam", callingCode: "673", flag: FLAG.Brunei },
  { name: "Papua New Guinea", callingCode: "675", flag: FLAG.Papuanewguinea },
  { name: "Tonga", callingCode: "676", flag: FLAG.Tonga },
  { name: "Solomon Islands", callingCode: "677", flag: FLAG.Solomonislands },
  { name: "Vanuatu", callingCode: "678", flag: FLAG.Vanuatu },
  { name: "Fiji", callingCode: "679", flag: FLAG.Fiji },
  {
    name: "Palau",
    callingCode: "680",
    flag: require("../../assets/icons/flag/Palau.jpg"),
  },
  {
    name: "Cook Islands",
    callingCode: "682",
    flag: require("../../assets/icons/flag/Cook_Islands.jpg"),
  },

  { name: "American Samoa", callingCode: "1684", flag: FLAG.AmericanSamoa },

  { name: "Western Samoa", callingCode: "685", flag: FLAG.Samoa },
  { name: "New Caledonia", callingCode: "687", flag: FLAG.NewCaledonia },
  { name: "Tuvalu", callingCode: "688", flag: FLAG.Tuvalu },
  { name: "French Polynesia", callingCode: "689", flag: FLAG.FrenchPolynesia },
  {
    name: "Marshall Islands",
    callingCode: "692",
    flag: require("../../assets/icons/flag/Marshallislands.jpg"),
  },

  { name: "Midway Islands", callingCode: "1808", flag: FLAG.MidwayIslands },

  {
    name: "North Korea",
    callingCode: "850",
    flag: require("../../assets/icons/flag/Northkorea.jpg"),
  },
  { name: "Hong Kong", callingCode: "852", flag: FLAG.HongKong },
  { name: "Macau", callingCode: "853", flag: FLAG.Macau },
  { name: "Cambodia", callingCode: "855", flag: FLAG.Cambodia },
  { name: "Laos", callingCode: "856", flag: FLAG.Laos },
  { name: "Bangladesh", callingCode: "880", flag: FLAG.Bangladesh },
  { name: "Taiwan", callingCode: "886", flag: FLAG.Taiwan },

  { name: "Maldives", callingCode: "960", flag: FLAG.Maldives },
  { name: "Lebanon", callingCode: "961", flag: FLAG.Lebanon },
  { name: "Jordan", callingCode: "962", flag: FLAG.Jordan },
  { name: "Syria", callingCode: "963", flag: FLAG.Syria },
  { name: "Iraq", callingCode: "964", flag: FLAG.Iraq },
  { name: "Kuwait", callingCode: "965", flag: FLAG.Kuwait },
  { name: "Saudi Arabia", callingCode: "966", flag: FLAG.Saudiarabia },
  { name: "Yemen", callingCode: "967", flag: FLAG.Yemen },
  { name: "Oman", callingCode: "968", flag: FLAG.Oman },
  { name: "United Arab Emirates", callingCode: "971", flag: FLAG.UAE },
  { name: "Israel", callingCode: "972", flag: FLAG.Israel },
  { name: "Bahrain", callingCode: "973", flag: FLAG.Bahrain },
  { name: "Qatar", callingCode: "974", flag: FLAG.Qatar },
  { name: "Bhutan", callingCode: "975", flag: FLAG.Bhutan },
  { name: "Mongolia", callingCode: "976", flag: FLAG.Mongolia },
  { name: "Nepal", callingCode: "977", flag: FLAG.Nepal },

  { name: "Turkmenistan", callingCode: "993", flag: FLAG.Turkmenistan },
  { name: "Azerbaijan", callingCode: "994", flag: FLAG.Azerbaijan },
  { name: "Georgia", callingCode: "995", flag: FLAG.Georgia },
  { name: "Uzbekistan", callingCode: "998", flag: FLAG.Uzbekistan },

  { name: "Anguilla", callingCode: "1264", flag: FLAG.Anguilla },
  {
    name: "Antigua & Barbuda",
    callingCode: "1268",
    flag: FLAG.Antiguaandbarbuda,
  },
  {
    name: "Virgin Islands, British",
    callingCode: "1284",
    flag: FLAG.BritishVirginIslands,
  },
  {
    name: "Virgin Islands, U.S.",
    callingCode: "1340",
    flag: FLAG.USVirginIslands,
  },
  { name: "Cayman Islands", callingCode: "1345", flag: FLAG.CaymanIslands },
  { name: "Grenada", callingCode: "1473", flag: FLAG.Grenada },
  {
    name: "Turks & Caicos Islands",
    callingCode: "1649",
    flag: FLAG.TurksAndCaicosIslands,
  },
  { name: "Montserrat", callingCode: "1664", flag: FLAG.Montserrat },
  {
    name: "Northern Mariana Islands",
    callingCode: "1670",
    flag: FLAG.NorthernMarianaIslands,
  },
  { name: "Guam", callingCode: "1671", flag: FLAG.Guam },
  { name: "St. Lucia", callingCode: "1758", flag: FLAG.SaintLucia },
  { name: "Dominica", callingCode: "1767", flag: FLAG.Dominica },
  {
    name: "St. Vincents & Grenadines",
    callingCode: "1784",
    flag: FLAG.SaintVincentAndTheGrenadines,
  },
  { name: "Puerto Rico", callingCode: "1787,1939", flag: FLAG.PuertoRico },
  {
    name: "Dominican Republic",
    callingCode: "1809,1829,1849",
    flag: FLAG.Dominicanrepublic,
  },
  {
    name: "Trinidad & Tobago",
    callingCode: "1868",
    flag: FLAG.TrinidadAndTobago,
  },
  {
    name: "St. Kitts & Nevis",
    callingCode: "1869",
    flag: FLAG.SaintKittsAndNevis,
  },
  { name: "Jamaica", callingCode: "1876", flag: FLAG.Jamaica },
];

if (__DEV__) {
  for (const c of PHONE_COUNTRIES) {
    if (!c.flag) {
      console.warn("[PHONE_COUNTRIES] Missing flag for:", c.name);
    }
    if (!c.callingCode || !c.callingCode.trim()) {
      console.warn("[PHONE_COUNTRIES] Missing callingCode for:", c.name);
    }
  }
}
